#!/usr/bin/env python3

import argparse
from collections import Counter
from datetime import datetime, timezone
import json
from pathlib import Path
import unicodedata
import urllib.parse
import urllib.request


SOURCES = [
    ("en", "English", "Machine learning"),
    ("fr", "French", "Apprentissage automatique"),
    ("de", "German", "Maschinelles Lernen"),
    ("es", "Spanish", "Aprendizaje automático"),
    ("pt", "Portuguese", "Aprendizado de máquina"),
    ("it", "Italian", "Apprendimento automatico"),
]

USER_AGENT = "MLClassLanguageDemo/1.0 (educational material)"


def fetch_article(language_code, title):
    parameters = urllib.parse.urlencode(
        {
            "action": "query",
            "prop": "extracts|revisions",
            "explaintext": 1,
            "redirects": 1,
            "rvprop": "ids|timestamp",
            "titles": title,
            "format": "json",
            "formatversion": 2,
        }
    )
    request = urllib.request.Request(
        f"https://{language_code}.wikipedia.org/w/api.php?{parameters}",
        headers={"User-Agent": USER_AGENT},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        page = json.load(response)["query"]["pages"][0]

    if page.get("missing"):
        raise RuntimeError(f"Wikipedia page not found: {language_code}:{title}")

    revision = page["revisions"][0]
    return {
        "title": page["title"],
        "pageid": page["pageid"],
        "revid": revision["revid"],
        "timestamp": revision["timestamp"],
        "extract": page["extract"],
    }


def is_latin_letter(character):
    return unicodedata.category(character).startswith("L") and "LATIN" in unicodedata.name(
        character, ""
    )


def clean_text(text):
    characters = []
    pending_space = False

    for character in unicodedata.normalize("NFC", text).lower():
        if is_latin_letter(character):
            if pending_space and characters:
                characters.append(" ")
            characters.append(character)
            pending_space = False
        else:
            pending_space = True

    return "".join(characters)


def count_features(text):
    return Counter(text), Counter(zip(text, text[1:]))


def build_models():
    records = []
    alphabet = set()

    for language_code, language_name, requested_title in SOURCES:
        article = fetch_article(language_code, requested_title)
        cleaned = clean_text(article.pop("extract"))
        unigram_counts, bigram_counts = count_features(cleaned)
        alphabet.update(unigram_counts)

        records.append(
            {
                "id": language_code,
                "name": language_name,
                "source": {
                    "title": article["title"],
                    "pageid": article["pageid"],
                    "revid": article["revid"],
                    "timestamp": article["timestamp"],
                    "url": (
                        f"https://{language_code}.wikipedia.org/w/index.php?"
                        f"title={urllib.parse.quote(article['title'].replace(' ', '_'))}"
                        f"&oldid={article['revid']}"
                    ),
                },
                "unigramTotal": sum(unigram_counts.values()),
                "bigramTotal": sum(bigram_counts.values()),
                "unigrams": dict(sorted(unigram_counts.items())),
                "bigrams": {
                    "".join(pair): count for pair, count in sorted(bigram_counts.items())
                },
            }
        )

    return {
        "generatedAt": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "smoothing": 1,
        "alphabet": sorted(alphabet),
        "languages": records,
    }


def main():
    parser = argparse.ArgumentParser(
        description="Build character-language models from localized Wikipedia articles."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).with_name("model-data.js"),
    )
    args = parser.parse_args()

    models = build_models()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(models, ensure_ascii=False, indent=2, sort_keys=True)
    args.output.write_text(
        "// Generated by language-id/build_language_models.py\n"
        f"window.LANGUAGE_MODEL_DATA = {payload};\n",
        encoding="utf-8",
    )

    for language in models["languages"]:
        print(
            f"{language['name']}: {language['unigramTotal']:,} characters, "
            f"{len(language['bigrams']):,} observed bigrams"
        )
    print(f"Alphabet: {len(models['alphabet'])} characters")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
